-- Generating report
select 
tab.keyName, 
tab.comment,
tab.value as en, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='ar') as ar, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='cs') as cs, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='da') as da, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='de') as de, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='el') as el, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='es') as es, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='es_MX') as es_MX, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='et') as et, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='fi') as fi, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='fr') as fr, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='fr_CA') as fr_CA, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='hu') as hu, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='in') as 'in', 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='is') as 'is', 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='it') as it, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='ja') as ja, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='ko') as ko, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='lt') as lt, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='lv') as lv, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='ms') as ms, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='nb') as nb, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='nl') as nl, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='pl') as pl, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='pt_BR') as pt_BR, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='ru') as ru, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='sk') as sk, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='sv') as sv, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='th') as th,
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='tr') as tr, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='uk') as uk, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='vi') as vi, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='zh_CN') as zh_CN, 
(select value from I18N_TRANSLATION where keyName=tab.keyName and locale='zh_TW') as zh_TW
from I18N_TRANSLATION as tab where locale='en' and comment like 'CP;%';
